name: Deploy Propti Nightly
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'FDS version'
        required: true
        type: string
env:
  REGISTRY: ghcr.io
  ORG: firedynamics
  IMAGE_NAME: propti-nightly
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          provenance: false
          file: docker/Dockerfile.nightly
          build-args: |
            FDS_VERSION=${{ inputs.tag }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG }}/${{ env.IMAGE_NAME }}:${{ inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}