name: Update All Propti Nightly Images
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - '**.py'
      - '.dockerignore'
      - 'docker/Dockerfile.nightly'
env:
  IMAGE_NAME: propti-nightly
jobs:
  trigger-updates:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      actions: write
    steps:
      - name: Extract available docker image versions and trigger build
        continue-on-error: true
        run: |
          REGEX=[0-9]+\.[0-9]+\.[0-9]+
          VERSIONS=$(curl --silent "https://api.github.com/users/${{ github.repository_owner }}/packages/container/${{ env.IMAGE_NAME }}/versions" --stderr - \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" | \
            grep -E "[[:space:]]+\"${REGEX}\"" | grep -oEi ${REGEX})
          for VERSION in ${VERSIONS}; do
            curl -L -X POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy.nightly.yaml/dispatches \
            -d "{\"ref\":\"master\",\"inputs\": {\"tag\": \"${VERSION}\"}}"
          done